# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
name: Deploy Python package to Azure Web App as a Linux web app.
on:
  push:
    branches:
      - api
  workflow_dispatch:
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
# See this in-depth article on CI for Python applications: https://azure.github.io/AppService/2020/12/11/cicd-for-python-apps.html
#
# 1. Set up the following secrets in your repository:
#   AZURE_CREDENTIALS_GITHUB_SECRET
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: 'semantic-seg'     # set this to your application's name
  WORKING_DIRECTORY: '.'        # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: '3.11'        # set the version to use

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
      id-token: write #This is required for requesting the JWT
  steps:
  # checkout the repo
  - uses: actions/checkout@v3
  # setup python
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
     python-version: ${{ env.PYTHON_VERSION }}
  # install dependencies
  - name: python install
    working-directory: ${{ env.WORKING_DIRECTORY }}
    run: |
     sudo apt-get update
     sudo apt-get install -y python${{ env.PYTHON_VERSION }}-venv
     sudo apt-get install -y libgl1-mesa-glx  # Necessary for opencv-python
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install --upgrade pip
     pip install setuptools
     pip install -r requirements.txt

  - name: Run Az CLI script
    run: |
      mkdir models/unet
      cd models/unet
      az storage blob download \
      --account-name cvmodels \
      --container-name models  \
      --name mini_unet_hd_complete.h5 \
      --file mini_unet_hd_complete.h5 \
      --account-key lNw5UtQJv83ZPvea4P1ZniA8Miwa7JlXDNhHSnzKJayT86PG+ZtlmLYuLldy+y4NTxerrF4yS8Tl+AStjvdw0A== \
      --auth-mode key

  # Azure login
  # - uses: azure/login@v1
  #   with:
  #    creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

  - name: Login to Azure
    uses: azure/login@v1
    with:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_028BE8AA7F9D4C00A06DCBE56B01C0EB }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D6D3B48ACAE407C92D34E013AE8346F }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C4B29017693B4BDFB8A96035E34A4646 }}

  - uses: azure/appservice-settings@v1
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     mask-inputs: false
     general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
  # deploy web app
  - uses: azure/webapps-deploy@v2
    id: deploy-to-webapp
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     package: ${{ env.WORKING_DIRECTORY }}

  # Azure logout
  - name: logout
    run: |
     az logout
